### ISSUE TITLE
[feature_request] Adds ability to switch gazebo hardware interface

### ISSUE THREAD

**Issue by rickstaa** [frankaemika/franka_ros#161]
I think it would be handy to have the ability to switch the `hardware_interface` that is used in the gazebo simulation for controlling the panda arm. This feature would allow users to test control the robot using different hardware interfaces, similar to the real robot. 

Currently,  the `hardware_interface/JointEffortInterface` is hardcoded into the [panda_arm.urdf.xacro](https://github.com/frankaemika/franka_ros/blob/356ec114c488c75edeaf5315633359459d37af31/franka_description/robots/panda_arm.urdf.xacro#L34-L35) file. Because of this, the release of the Noetic [panda_moveit_config](https://github.com/ros-planning/panda_moveit_config) package, which targets franka_ros v0.8.0, is blocked, as we would like to both use the `JointPositionInterface` in the gazebo simulation and on the real robot (see https://github.com/ros-planning/panda_moveit_config/pull/74 and https://github.com/ros-planning/panda_moveit_config/pull/68).

I also tried switching to the `effort_controllers/JointTrajectoryController` while using the following pid gains:

```yaml
effort_joint_trajectory_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - panda_joint1
    - panda_joint2
    - panda_joint3
    - panda_joint4
    - panda_joint5
    - panda_joint6
    - panda_joint7
  gains:
    panda_joint1: { p: 12000, d: 50, i: 0.0, i_clamp: 10000 }
    panda_joint2: { p: 30000, d: 100, i: 0.02, i_clamp: 10000 }
    panda_joint3: { p: 18000, d: 50, i: 0.01, i_clamp: 1 }
    panda_joint4: { p: 18000, d: 70, i: 0.01, i_clamp: 10000 }
    panda_joint5: { p: 12000, d: 70, i: 0.01, i_clamp: 1 }
    panda_joint6: { p: 7000, d: 50, i: 0.01, i_clamp: 1 }
    panda_joint7: { p: 2000, d: 20, i: 0.0, i_clamp: 1 }
```

Unfortunately, although these gains seem decent on the simulation robot (i.e. control has a slight offset), they lead to dangerous situations (i.e. very high velocities and acceleration) on the real robot, which causes the software emergency stop to be invoked).

I created #156 and #157 to add this feature.
