### ISSUE TITLE
The initial state of the robot is not updated within Moveit using EffortJointTrajectoryController

### ISSUE THREAD

**Issue by TomasMerva** [frankaemika/franka_ros#231]
Hi, I have set the `effort_joint_trajectory_controller` with the official `panda_moveit_config` and `franka_ros` packages. When I test it with MotionPlanning Rviz plugin, the `Start State` of the robot is updated only once right after launching the plugin and thereafter it is not. In other words, after moving the robot, the `Start State` remains the same and it differs from `tf`, which is correct and same as the physical robot. The problem is not happening when I am using `position_joint_trajectory_controller`. I am guessing that I forgot to change the topic name somewhere, but cannot find anything. What can be the problem?

My panda_moveit_config/config/panda_controllers/:
```
controller_list:
  - name: effort_joint_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
```

![image](https://user-images.githubusercontent.com/19751317/158544084-33b4ee24-77f1-4edc-82ac-52b21c18d3d0.png)
![image](https://user-images.githubusercontent.com/19751317/158544159-cd382c8a-306a-4be1-b53c-eb757b72d7c8.png)
