### ISSUE TITLE
Could not switch controllers

### ISSUE THREAD

**Issue by BolunDai0216** [frankaemika/franka_ros#272]
Hi,

I was trying to start creating my own custom controller. So the first thing I did was to try and create a really simple .yaml file with the standard controller types:

```yaml
panda:
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: panda_joint1
    pid: { p: 100.0, i: 0.01, d: 10.0 }
```

However, I got the following error:

```console
[ERROR] [1658503332.265323172]: Could not switch controllers. The hardware interface combination for the requested controllers is unfeasible.
[ERROR] [1658503332.265997, 0.000000]: Failed to start controllers: franka_state_controller, panda/joint1_position_controller
```

Is it possible to help me see what the issue is here? I did not find much information online. I thought since `joint1` has

```xml
  <transmission name="panda_joint1_transmission">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="panda_joint1">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="panda_joint1_motor">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </actuator>
  </transmission>
```

the hardware interface and controller combination should work.

Thanks in advance!
